models:
  qwen3:
    model: ai/qwen3:0.6B-Q4_0

services:

  mcp-gateway:
    image: docker/mcp-gateway
    command:
      - --servers=github
      - --tools=search_repositories
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

  chat-backend:
    build: .
    ports:
      - "3001:3001"
    models:
      qwen3:
        endpoint_var: MODEL_BASE_URL
    depends_on:
      - mcp-gateway
