models:
  qwen3:
    model: ai/qwen3:0.6B-Q4_0

services:

  #
  # https://github.com/docker/mcp-gateway/blob/main/examples/container/README.md
  # https://github.com/docker/mcp-gateway/blob/main/examples/interceptors/compose.yaml
  #
  mcp-gateway:
    image: docker/mcp-gateway
    command:
      - --transport=streaming
      - --servers=curl
      - --servers=github
      - --verbose=true
      - --port=9011
    ports:
      - 9011:9011
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: wget -O- http://localhost:9011/health
      interval: 1s
      timeout: 2s
      retries: 60
      start_period: 2s

  chat-backend:
    build: .
    environment:
      - MCP_HOST=http://mcp-gateway:9011/mcp
    ports:
      - "3001:3001"
    models:
      qwen3:
        endpoint_var: MODEL_BASE_URL
    depends_on:
      mcp-gateway:
        condition: service_healthy
