FROM nvidia/cuda:12.8.1-base-ubuntu22.04

USER root

RUN apt-get update -qyy \
    && apt-get install -qyy \
        build-essential \
        wget \
        curl \
        git \
        python3-pip \
        python3-dev \
        python3-venv \
    && apt-get clean

WORKDIR /app

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip
RUN pip install axolotl

COPY axolotl_config.yaml config.yaml

CMD ["axolotl", "train", "config.yaml"]
