#
# docker build . -f Dockerfile.dev -t laravel-prism --build-arg COMPOSER_HASH=dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6
# docker run -v ${USERPROFILE:-~}/.npmrc:/root/.npmrc -v ${USERPROFILE:-~}/.composer:/root/.composer -v .:/var/task -p 8080:8080 -p 5173:5173 laravel-prism
#
FROM ghcr.io/abenevaut/vapor-nginx:php83

RUN apk --update add \
        nodejs \
        npm \
# Remove alpine cache
    && rm -rf /var/cache/apk/*

# Add configuration files
COPY --chown=nobody rootfs/ /
RUN chmod +x /etc/service/*/run

ENV COMPOSER_HOME=/composer \
    PATH=/composer/vendor/bin:$PATH

ARG COMPOSER_HASH
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === '${COMPOSER_HASH}') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && php -r "unlink('composer-setup.php');"
