#
# docker-compose up -d --build
#
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/app/

  exploit:
    image: alpine/lynx
    extra_hosts:
      - my-fake-domain:172.27.0.2

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    depends_on:
      - app
